services:
  postgres:
    image: postgres:15-alpine
    container_name: nextjs-postgres
    restart: always
    environment:
      - POSTGRES_DB=nextjs_app
      - POSTGRES_USER=nextjs_user
      - POSTGRES_PASSWORD=nextjs_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextjs_user -d nextjs_app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
