services:
    app:
        container_name: nextjs-app
        build:
            context: .
            target: dev
        restart: always
        command: sh -c "yarn docker:drizzle:push && yarn dev"
        environment:
            - NODE_ENV=development
            - DATABASE_URL=file:./dev.db
            - NEXTAUTH_URL=http://localhost:3000
            - NEXTAUTH_SECRET=development-secret-key
            - NEXT_PUBLIC_DOMAIN=localhost
            - ACCESS_TOKEN=session-token
        volumes:
            - .:/app
            - node_modules_cache:/app/node_modules
            - next_cache:/app/.next
        ports:
            - "3000:3000"

volumes:
    node_modules_cache:
    next_cache:
